--- drivers/media/video/msm/sensors/Makefile
+++ drivers/media/video/msm/sensors/Makefile
@@ -5,6 +5,7 @@
 obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor.o
 obj-$(CONFIG_OV5647) += ov5647_v4l2.o
 obj-$(CONFIG_IMX091) += imx091_v4l2.o
+obj-$(CONFIG_IMX105) += imx105_v4l2.o
 obj-$(CONFIG_IMX175) += imx175_v4l2.o
 obj-$(CONFIG_MACH_ELITE) += imx175_2lane_v4l2.o
 obj-$(CONFIG_MACH_JET) += imx175_2lane_v4l2.o
